//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.07 at 12:03:06 PM CET 
//


package impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import Encheres.xml.EnchereType;
import Encheres.xml.EtatEnchere;
import Encheres.xml.PersonneType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnchereType", propOrder = {
    "prix",
    "propri\u00e9taire",
    "meilleurPrix",
    "titre",
    "descriptif",
    "etat"
})
public class EnchereTypeImpl
    implements EnchereType
{

    protected int prix;
    @XmlElement(required = true, type = PersonneTypeImpl.class)
    protected PersonneTypeImpl propriétaire;
    @XmlElement(name = "MeilleurPrix", required = true)
    protected String meilleurPrix;
    @XmlElement(name = "Titre", required = true)
    protected String titre;
    @XmlElement(name = "Descriptif", required = true)
    protected String descriptif;
    @XmlElement(name = "Etat", required = true)
    protected EtatEnchere etat;

    public int getPrix() {
        return prix;
    }

    public void setPrix(int value) {
        this.prix = value;
    }

    public PersonneType getPropriétaire() {
        return propriétaire;
    }

    public void setPropriétaire(PersonneType value) {
        this.propriétaire = ((PersonneTypeImpl) value);
    }

    public String getMeilleurPrix() {
        return meilleurPrix;
    }

    public void setMeilleurPrix(String value) {
        this.meilleurPrix = value;
    }

    public String getTitre() {
        return titre;
    }

    public void setTitre(String value) {
        this.titre = value;
    }

    public String getDescriptif() {
        return descriptif;
    }

    public void setDescriptif(String value) {
        this.descriptif = value;
    }

    public EtatEnchere getEtat() {
        return etat;
    }

    public void setEtat(EtatEnchere value) {
        this.etat = value;
    }

}
