//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.07 at 12:03:06 PM CET 
//


package impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import Encheres.xml.PersonneType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonneType", propOrder = {
    "nom",
    "prenom",
    "login",
    "mail"
})
public class PersonneTypeImpl
    implements PersonneType
{

    @XmlElement(name = "Nom", required = true)
    protected String nom;
    @XmlElement(name = "Prenom", required = true)
    protected String prenom;
    @XmlElement(name = "Login", required = true)
    protected String login;
    @XmlElement(name = "Mail", required = true)
    protected String mail;

    public String getNom() {
        return nom;
    }

    public void setNom(String value) {
        this.nom = value;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String value) {
        this.prenom = value;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String value) {
        this.login = value;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String value) {
        this.mail = value;
    }

}
