package Encheres.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.07 at 12:03:06 PM CET 
//


/**
 * <p>Java class for EnchereType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnchereType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prix" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="propriétaire" type="{}PersonneType"/>
 *         &lt;element name="MeilleurPrix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Titre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Descriptif" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Etat" type="{}EtatEcnchere"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface EnchereType {


    /**
     * Gets the value of the prix property.
     * 
     */
    int getPrix();

    /**
     * Sets the value of the prix property.
     * 
     */
    void setPrix(int value);

    /**
     * Gets the value of the propriétaire property.
     * 
     * @return
     *     possible object is
     *     {@link PersonneType }
     *
     */
    PersonneType getPropriétaire();

    /**
     * Sets the value of the propriétaire property.
     *
     * @param value
     *     allowed object is
     *     {@link PersonneType }
     *
     */
    void setPropriétaire(PersonneType value);

    /**
     * Gets the value of the meilleurPrix property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    String getMeilleurPrix();

    /**
     * Sets the value of the meilleurPrix property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    void setMeilleurPrix(String value);

    /**
     * Gets the value of the titre property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    String getTitre();

    /**
     * Sets the value of the titre property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    void setTitre(String value);

    /**
     * Gets the value of the descriptif property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    String getDescriptif();

    /**
     * Sets the value of the descriptif property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    void setDescriptif(String value);

    /**
     * Gets the value of the etat property.
     *
     * @return
     *     possible object is
     *     {@link EtatEnchere }
     *
     */
    EtatEnchere getEtat();

    /**
     * Sets the value of the etat property.
     *
     * @param value
     *     allowed object is
     *     {@link EtatEnchere }
     *     
     */
    void setEtat(EtatEnchere value);

}
