package Encheres.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.07 at 12:03:06 PM CET 
//


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EtatEcnchere.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EtatEcnchere">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ouvert"/>
 *     &lt;enumeration value="fermé"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EtatEcnchere")
@XmlEnum
public enum EtatEnchere {

    @XmlEnumValue("ouvert")
    OUVERT("ouvert"),
    @XmlEnumValue("ferm\u00e9")
    FERMÉ("ferm\u00e9");
    private final String value;

    EtatEnchere(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EtatEnchere fromValue(String v) {
        for (EtatEnchere c: EtatEnchere.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
